export const CURRENCYLIST = [
    {id: "AUD", label: "Australia Dollar"},
    {id: "BGN", label: "Bulgaria Lev"},
    {id: "BRL", label: "Brazil Real"},
    {id: "CAD", label: "Canada Dollar"},
    {id: "CHF", label: "Switzerland Franc"},
    {id: "CNY", label: "China Yuan Renminbi"},
    {id: "CZK", label: "Czech Republic Koruna"},
    {id: "DKK", label: "Denmark Krone"},
    {id: "EUR", label: "Euro Member Countries"},
    {id: "GBP", label: "United Kingdom Pound"},
    {id: "HKD", label: "Hong Kong Dollar"},
    {id: "HRK", label: "Croatia Kuna"},
    {id: "HUF", label: "Hungary Forint"},
    {id: "IDR", label: "Indonesia Rupiah"},
    {id: "ILS", label: "Israel Shekel"},
    {id: "INR", label: "India Rupee"},
    {id: "JPY", label: "Japan Yen"},
    {id: "KRW", label: "Korea (South) Won"},
    {id: "MXN", label: "Mexico Peso"},
    {id: "MYR", label: "Malaysia Ringgit"},
    {id: "NOK", label: "Norway Krone"},
    {id: "NZD", label: "New Zealand Dollar"},
    {id: "PHP", label: "Philippines Peso"},
    {id: "PLN", label: "Poland Zloty"},
    {id: "RON", label: "Romania Leu"},
    {id: "RUB", label: "Russia Ruble"},
    {id: "SEK", label: "Sweden Krona"},
    {id: "SGD", label: "Singapore Dollar"},
    {id: "THB", label: "Thailand Baht"},
    {id: "TRY", label: "Turkey Lira"},
    {id: "USD", label: "United States Dollar"},
    {id: "ZAR", label: "Zimbabwe Dollar"}
]